### ISSUE TITLE
Invalid signature. Expected signature base string: POST

### ISSUE THREAD

**Issue by cecnic1989** [ScrumDoLLC/ScrumDoAPIV2#2]
I'm using the oAuth 1.0 method of authenticating the user on my nodejs application.  I'm able to get past the request_token and authorize steps.  I'm getting this error when requesting for the access_token.  The signing algorithm that I'm using is HMAC-SHA1.  Any ideas why I'm getting this invalid signature response?

```
{
  "Invalid signature. Expected signature base string: POST": "",
  "https://www.scrumdo.com/api/v2/oauth/access_token/": "",
 "oauth_consumer_key=yEM7RDwHuH9SwEFFz5&oauth_nonce=cc67de2a42764d398829c6b8ce0c7c73&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1475870228&oauth_token=Qdg4nwmRppRxw64UdH&oauth_verifier=tLPHEdzdG2&oauth_version=1.0": ""
}
```

**Comment by marc-hughes** [comment]
First, let's make sure you're using the right version of the API. If you're using the 'current' version of scrumdo (the orange themed one) you want V3 of the api found here:

https://github.com/ScrumDoLLC/ScrumDoAPIv3

The main difference is the hostname to use (app.scrumdo.com instead of www.scrumdo.com)
Now, on to your specific question. We have an example app that authenticates via OAuth with ScrumDo that you can try out here: 

Classic: https://github.com/ScrumDoLLC/ScrumDoAPIv2/tree/master/examples/django  

New/Current version: https://github.com/ScrumDoLLC/ScrumDoAPIv3/tree/master/examples/django

**Comment by cecnic1989** [comment]
I was able to properly authenticate by switching the version to V3.
